export const CONSTANTS = {
	invalidCrossSiteSameShiftError : {
		severity: 'error',
		summary: 'Incorrect Assignment',
		detail: 'User cannot be assigned on same shift for cross site'
	},
	submitReportSuccess : {
		severity: 'success',
		summary: 'Report Submitted',
		detail: 'successfully'
	},
	errorMessage: {
		severity: 'error',
		summary: '',
		detail: ''
	},
	successMessage: {
		severity: 'success',
		summary: '',
		detail: ''
	},
	auditRequestProps: [
		'user_id',
		'attendance',
		'ot',
		'cross_ot',
		'night_day_ot',
		'night_day_cross_ot',
		'grooming_failure',
		'beard',
		'uniform',
		'shoes',
		'socks',
		'accessories',
		'hair_cut',
		'idf',
		'comments',
		'adhoc'
	],
	auditAdhocRequestProps: [
		'user_id',
		'assigned_role_id',
		'attendance',
		'ot',
		'cross_ot',
		'night_day_ot',
		'night_day_cross_ot',
		'grooming_failure',
		'beard',
		'uniform',
		'shoes',
		'socks',
		'accessories',
		'hair_cut',
		'idf',
		'comments',
		'adhoc'
	],
	callReportingColumns: [
		{ field: 'actions', header: 'Actions', width: '100px', show: true },
		{ field: 'role', header: 'Role', width: '200px', show: true },
		{ field: 'name', header: 'Name', width: '200px', show: true },
		{ field: 'user_id', header: 'Code', width: '200px', show: true },
		{ field: 'contact_number', header: 'Contact', width: '200px', show: true },
		{ field: 'attendance', header: 'Attendance', width: '100px', show: true },
		{ field: 'beard', header: 'Shaved', width: '100px', show: true },
		{ field: 'uniform', header: 'Uniform', width: '100px', show: true },
		{ field: 'shoes', header: 'Shoes', width: '100px', show: true },
		{ field: 'socks', header: 'Socks', width: '100px', show: true },
		{ field: 'accessories', header: 'Accessories', width: '100px', show: true },
		{ field: 'hair_cut', header: 'Haircut', width: '100px', show: true },
		{ field: 'idf', header: 'ID Failure', width: '100px', show: true },
		{ field: 'comments', header: 'Comments', width: '200px', show: true }
	],
	callReportingAdhocColumns: [
		{ field: 'actions', header: 'Actions', width: '100px', show: true },
		{ field: 'role', header: 'Role', width: '200px', show: true },
		{ field: 'name', header: 'Name', width: '200px', show: true },
		{ field: 'user_id', header: 'Code', width: '200px', show: true },
		{ field: 'assigned_role', header: 'Assigned Role', width: '200px', show: true },
		{ field: 'attendance', header: 'Attendance', width: '100px', show: true },
		{ field: 'beard', header: 'Shaved', width: '100px', show: true },
		{ field: 'uniform', header: 'Uniform', width: '100px', show: true },
		{ field: 'shoes', header: 'Shoes', width: '100px', show: true },
		{ field: 'socks', header: 'Socks', width: '100px', show: true },
		{ field: 'accessories', header: 'Accessories', width: '100px', show: true },
		{ field: 'hair_cut', header: 'Haircut', width: '100px', show: true },
		{ field: 'idf', header: 'ID Failure', width: '100px', show: true },
		{ field: 'comments', header: 'Comments', width: '200px', show: true }
	],
	viewReportColumns: [
		{ field: 'reporting_date', headerName: 'Date', filter: 'agSetColumnFilter', pinned: 'left'},
		{ field: 'site_name', headerName: 'Site Name', filter: 'agSetColumnFilter', pinned: 'left'},
		// { field: 'zone', headerName: 'Zone', filter: 'agSetColumnFilter'}
	],
	adhocNewUsersCols: [
		{ field: 'actions', header: 'Actions', width: '70px', show: true },
		{ field: 'role', header: 'Role', width: '140px', show: true },
		{ field: 'code', header: 'Code', width: '140px', show: true },
		{ field: 'firstname', header: 'Firstname', width: '140px', show: true },
		{ field: 'middlename', header: 'Middlename', width: '140px', show: true },
		{ field: 'lastname', header: 'Lastname', width: '140px', show: true },
		{ field: 'dob', header: 'DOB', width: '245px', show: true },
		{ field: 'gender', header: 'Gender', width: '140px', show: true },
		{ field: 'address', header: 'Address', width: '140px', show: true },
		{ field: 'pan', header: 'PAN', width: '140px', show: true },
		{ field: 'adhaar', header: 'ADHAAR', width: '140px', show: true },
		{ field: 'verified', header: 'Verified', width: '50px', show: true },
		{ field: 'contact_number', header: 'Contact Number', width: '140px', show: true },
		{ field: 'alternate_contact_number', header: 'Alternate Contact Number', width: '140px', show: true },
		{ field: 'active', header: 'Active', width: '50px', show: true },
	],
	adhocNewUserCreateRequestProps: [
		'role_id',
		'code',
		'firstname',
		'middlename',
		'lastname',
		'dob',
		'gender',
		'address',
		'pan',
		'adhaar',
		'verified',
		'contact_number',
		'alternate_contact_number',
		'active'
	],
	adhocNewUserUpdateRequestProps: [
		'id',
		'role_id',
		'code',
		'firstname',
		'middlename',
		'lastname',
		'dob',
		'gender',
		'address',
		'pan',
		'adhaar',
		'verified',
		'contact_number',
		'alternate_contact_number',
		'active'
	],
	adhocNewUserDeleteRequestProps: [
		'id'
	],
	usersCols: [
		{ field: 'actions', header: 'Actions', width: '70px', show: true },
		{ field: 'role', header: 'Role', width: '140px', show: true },
		{ field: 'code', header: 'Code', width: '140px', show: true },
		{ field: 'firstname', header: 'Firstname', width: '140px', show: true },
		{ field: 'middlename', header: 'Middlename', width: '140px', show: true },
		{ field: 'lastname', header: 'Lastname', width: '140px', show: true },
		{ field: 'dob', header: 'DOB', width: '245px', show: true },
		{ field: 'gender', header: 'Gender', width: '140px', show: true },
		{ field: 'address', header: 'Address', width: '140px', show: true },
		{ field: 'pan', header: 'PAN', width: '140px', show: true },
		{ field: 'adhaar', header: 'ADHAAR', width: '140px', show: true },
		{ field: 'verified', header: 'Verified', width: '50px', show: true },
		{ field: 'contact_number', header: 'Contact Number', width: '140px', show: true },
		{ field: 'alternate_contact_number', header: 'Alternate Contact Number', width: '140px', show: true },
		{ field: 'active', header: 'Active', width: '50px', show: true },
	],
	userCreateRequestProps: [
		'role_id',
		'code',
		'firstname',
		'middlename',
		'lastname',
		'dob',
		'gender',
		'address',
		'pan',
		'adhaar',
		'adhaar_name',
		'start_date',
		'end_date',
		'linked_site_code',
		'verified',
		'contact_number',
		'alternate_contact_number',
		'active'
	],
	userUpdateRequestProps: [
		'id',
		'role_id',
		'code',
		'firstname',
		'middlename',
		'lastname',
		'dob',
		'gender',
		'address',
		'pan',
		'adhaar',
		'adhaar_name',
		'start_date',
		'end_date',
		'linked_site_code',
		'verified',
		'contact_number',
		'alternate_contact_number',
		'active'
	],
	userDeleteRequestProps: [
		'id'
	]
};